# Generated by Django 5.2.4 on 2025-07-17 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='waste_type',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Organic', 'Organic'), ('E-waste', 'E-waste'), ('Metal', 'Metal'), ('Glass', 'Glass'), ('Other', 'Other')], max_length=100),
        ),
    ]
