# Generated by Django 5.2.4 on 2025-07-17 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_alter_report_waste_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='waste_type',
            field=models.CharField(choices=[], max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='assigned_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste.company'),
        ),
    ]
