# Generated by Django 5.2.4 on 2025-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0003_company_alter_report_status_alter_report_waste_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
