# Generated by Django 5.2.4 on 2025-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0004_company_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='waste_type',
            field=models.CharField(choices=[('Plastic', 'Plastic'), ('Organic', 'Organic'), ('E-waste', 'E-waste'), ('Metal', 'Metal'), ('Glass', 'Glass'), ('Other', 'Other')], max_length=100),
        ),
    ]
