# Generated by Django 5.2.4 on 2025-07-19 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0006_report_latitude_report_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Full', 'Full')], max_length=30)),
                ('types', models.CharField(max_length=200)),
            ],
        ),
    ]
