# Generated by Django 5.2.12 on 2026-03-11 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0010_pickuprequest_latitude_pickuprequest_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='preferred_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_requests', to='waste.company'),
        ),
    ]
