# Generated by Django 5.2.12 on 2026-03-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0011_pickuprequest_preferred_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
