# Generated by Django 5.2.12 on 2026-03-11 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0012_citizen_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='full_reports_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bin',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Full', 'Full')], default='Available', max_length=30),
        ),
        migrations.CreateModel(
            name='BinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='waste.bin')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste.citizen')),
            ],
            options={
                'unique_together': {('bin', 'reported_by')},
            },
        ),
    ]
